[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "all"

# Legacy dictionary term URLs redirect
[[redirects]]
  from = "/slownik-erp/:id-:slug"
  to = "/slownik-erp/:slug"
  status = 301
  force = true

[[redirects]]
  from = "/slownik-erp/:id-:slug.html"
  to = "/slownik-erp/:slug"
  status = 301
  force = true

# Dictionary term pages with edge function
[[edge_functions]]
  path = "/slownik-erp/*"
  function = "dictionary-term"

# System detail pages with edge function
[[edge_functions]]
  path = "/systemy-erp/*"
  function = "system-detail"

# Partner pages with edge function
[[edge_functions]]
  path = "/partnerzy/*"
  function = "partners"

# Dictionary term pages fallback
[[redirects]]
  from = "/slownik-erp/*"
  to = "/index.html"
  status = 200
  force = true
  conditions = {Cookie = ["__prerender_bypass"]}

# System detail pages fallback
[[redirects]]
  from = "/systemy-erp/*"
  to = "/index.html"
  status = 200
  force = true
  conditions = {Cookie = ["__prerender_bypass"]}

# Dictionary index page
[[redirects]]
  from = "/slownik-erp"
  to = "/index.html"
  status = 200
  force = true

# Other pages with SEO versions
[[redirects]]
  from = "/firmy-it"
  to = "/seo/firmy-it/index.html"
  status = 200
  conditions = {Cookie = ["__prerender_bypass"]}

[[redirects]]
  from = "/firmy-it"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/partnerzy/*"
  to = "/index.html"
  status = 200
  force = true
  conditions = {Cookie = ["__prerender_bypass"]}

[[redirects]]
  from = "/partnerzy"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/systemy-erp"
  to = "/seo/systemy-erp/index.html"
  status = 200
  conditions = {Cookie = ["__prerender_bypass"]}

[[redirects]]
  from = "/systemy-erp"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/kalkulator"
  to = "/seo/kalkulator/index.html"
  status = 200
  conditions = {Cookie = ["__prerender_bypass"]}

[[redirects]]
  from = "/kalkulator"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/porownaj-systemy-erp"
  to = "/seo/porownaj-systemy-erp/index.html"
  status = 200
  conditions = {Cookie = ["__prerender_bypass"]}

[[redirects]]
  from = "/porownaj-systemy-erp"
  to = "/index.html"
  status = 200

# Fallback redirect for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
