[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "all"

# Dictionary pages with edge function
[[edge_functions]]
  path = "/slownik-erp"
  function = "dictionary-term"

[[edge_functions]]
  path = "/slownik-erp/*"
  function = "dictionary-term"

# Handle trailing slashes
[[redirects]]
  from = "/slownik-erp/"
  to = "/slownik-erp"
  status = 301
  force = true

# Handle SEO bot requests
[[redirects]]
  from = "/slownik-erp"
  to = "/.netlify/functions/dictionary-term"
  status = 200
  force = true
  conditions = {User-Agent = ["Googlebot|bingbot|DuckDuckBot|facebookexternalhit|Twitterbot"]}

[[redirects]]
  from = "/slownik-erp/*"
  to = "/.netlify/functions/dictionary-term"
  status = 200
  force = true
  conditions = {User-Agent = ["Googlebot|bingbot|DuckDuckBot|facebookexternalhit|Twitterbot"]}

# Serve index.html for all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Other pages with SEO versions
[[redirects]]
  from = "/firmy-it"
  to = "/seo/firmy-it/index.html"
  status = 200
  conditions = {Cookie = ["__prerender_bypass"]}

[[redirects]]
  from = "/firmy-it"
  to = "/index.html"
  status = 200
