[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "all"

# Dictionary pages with edge function
[[edge_functions]]
  path = "/slownik-erp"
  function = "dictionary-term"

[[edge_functions]]
  path = "/slownik-erp/*"
  function = "dictionary-term"

# Dictionary pages fallback
[[redirects]]
  from = "/slownik-erp"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/slownik-erp/*"
  to = "/index.html"
  status = 200

# Other pages with SEO versions
[[redirects]]
  from = "/firmy-it"
  to = "/seo/firmy-it/index.html"
  status = 200
  conditions = {Cookie = ["__prerender_bypass"]}

[[redirects]]
  from = "/firmy-it"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/partnerzy"
  to = "/seo/partnerzy/index.html"
  status = 200
  conditions = {Cookie = ["__prerender_bypass"]}

[[redirects]]
  from = "/partnerzy"
  to = "/index.html"
  status = 200
